application:
  env: "staging"
  image: "anushahahaha/student-app:0.0.1-SNAPSHOT"
  configMap:
    port: "8080"
    dbPort: "5432"
    dbHost: "postgres.student-api-staging.svc.cluster.local"
    dbName: "student-db"

  deployment:
    replicaCount: "2"

database:
  name: "student-db"
  username: "postgres"
  password: "postgres"
  port: "5432"
  url: "jdbc:postgresql://postgres.student-api-staging.svc.cluster.local:5432/student-db"

ingress:
  className: "nginx"
  hosts:
    - host: "student-api.local"
      paths:
        - path: "/"
          pathType: "Prefix"
