apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
stringData:
  DB_NAME: {{ .Values.database.name }}
  DB_USERNAME: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_URL: {{ .Values.database.url }}
