apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-creds
  namespace: student-api-staging
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  data:
    - secretKey: username
      remoteRef:
        key: dockerhub
        property: username
    - secretKey: password
      remoteRef:
        key: dockerhub
        property: password
    - secretKey: email
      remoteRef:
        key: dockerhub
        property: email

  target:
    name: dockerhub-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "{{ `{{ .username }}` }}",
                "password": "{{ `{{ .password }}` }}",
                "email": "{{ `{{ .email }}` }}",
                "auth": "{{ `{{ printf "%s:%s" .username .password | b64enc }}` }}"
              }
            }
          }
