apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: student-api
spec:
  ingressClassName: nginx
  rules:
    - host: student-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-api
                port:
                  number: 80